### ISSUE TITLE
Multiple value lines for the same parameter

### ISSUE THREAD

**Issue by ElhNour** [microsoft/pict#104]
Hello, 
I have a large list of values for a single parameter (from 1 to 1000) that are displayed on multiple lines in the model (not just one). So, when I run PICT from the cli (`./pict model.txt > results.txt`), nothing happens because PICT expects a single line of values per parameter. 
However, when I tried to put less values (from 1 to 49 in order to have one line for this parameter), the program ran successfully.
Is there a way or workaround for the program to handle multiple lines of values for the same parameter?

**Comment by jaccz** [comment]
Are you sure it isn't working? PICT can take a long time to run on a large model. Observe memory usage of the PICT.EXE process and see if there are memory allocations happening.

Can you add the model here? (Or some sort of equivalent-in-size model if you are not comfortable sharing your real one.)

**Comment by ElhNour** [comment]
Thank you for your answer. Yes, I assume PICT is taking a long time to generate the experiments, because in fact the number of possible combinations is very big.
Here is the model:
X1: from 1 to 1000 
X2: from 1 to 1000
X3: from 1 to 5
X4: TRUE, FALSE

**Comment by ElhNour** [comment]
Yes, definitely. Thank you so much for your answers!
