### ISSUE TITLE
Does the api-usage have full functionality as cli?

### ISSUE THREAD

**Issue by happy2discover** [microsoft/pict#107]
I've read **[doc/pict.md](https://github.com/Microsoft/pict/blob/main/doc/pict.md)** and the **api-usage** sample. But I still don't know how to add some string values for a parameter via **api**.
Does the **api-usage** have full functionality as **cli**? I'm looking forward to your help. 😃

**Comment by jaccz** [comment]
You can't. It is just sets of indexes. It is up to the caller of the API to translate the indexes into user-readable elements.

**Comment by happy2discover** [comment]
Got it. Thanks for your answer.
