### ISSUE TITLE
Wrong test case generated

### ISSUE THREAD

**Issue by wa9035148** [Microsoft/pict#15]
-- The parameter settings--
comp_unit:            1,2,3
block_min_q:          0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
IF [comp_unit] = 2 AND [x1p2_mode] = 0 THEN [block_min_q] < 12;
x1p2_mode:            0,1

-- The test case generated--
 comp_unit x1p2_mode block_min_q
     2                  0              12
     2                  0              13

The question:
I think these test case should not be generated with above parameters and conditions.
But they appeared in the output. Since I am not very famillar with this tool. May be there were some mistake in my input file(the parametes and conditions).

**Comment by jacekczerwonka** [comment]
What's the actual content of the input model? As written above, the tool should fail parsing (constraints and parameter definitions should not mix).
