### ISSUE TITLE
Marking values as negative depending on constraint

### ISSUE THREAD

**Issue by few** [Microsoft/pict#18]
I find my self writing models with variables with possible values that can be positive or negative depending on the value of another variable. In Example1 the value "c2" is negative if `[A]="a2"`. To deal with this I duplicate the value "c2" and add a constraint as shown.
Is there a better way to deal with this, that doesn't involve duplicating "c2" like that? If not, would you consider adding syntax for this like Example2?
#### Example1 ####
```
A: a1, a2
B: b1, b2
C: c1, c2_positive, ~c2_negative
IF [A] = "a2" THEN
    [C] <> "c2_positive"
ELSE
    [C] <> "c2_negative";
```
#### Example2 - not supported! ####
```
A: a1, a2
B: b1, b2
C: c1, c2
IF [A] = "a2" THEN
    NEGATIVE([C] = "c2")
```

**Comment by jacekczerwonka** [comment]
Maybe it is me but I think your example 1 is actually easier to understand. Especially if these constructs are not that frequent (I haven't seen one like this before myself) then adding complexity to the syntax is probably not the best approach.
