### ISSUE TITLE
Bad performance with many constraints.

### ISSUE THREAD

**Issue by Bj-He** [Microsoft/pict#29]
- 22 parameters, each have 2-9 values.

- 9 constraints, including 8 like"IF THEN ELSE" and 1 like [a]<=[b] and 2 of the 'IF THEN ELSE' constraints are big like:

```
IF [sysbench] in {"oltp_read_only.lua",  "oltp_read_write.lua"} THEN 
	[--range-size] >= 0 AND
	[--point-selects] >= 0 AND
	[--simple-ranges] >= 0 AND
	[--sum-ranges] >= 0 AND
	[--order-ranges] >= 0 AND
	[--distinct-ranges] >= 0 AND
	[--range-selects] <> "nil"
 ELSE 
	[--range-size] = -1 AND
	[--point-selects] = -1 AND
	[--simple-ranges] = -1 AND
	[--sum-ranges] = -1 AND
	[--order-ranges] = -1 AND
	[--distinct-ranges] = -1 AND
	[--range-selects] = "nil";
```

- Then  I run with default configurations, the program hangs. I wait about 30min but nothing happens.

- if I reduce the constraints, e.g., remove one of the 'big' IF THEN ELSE, run with default configurations, it just takes about 10-20 sec.

Does the order of constraints matters? Or the algorithm is just exponential? 

Please help
Thank you.

**Comment by Bj-He** [comment]
oh, I think this is a dup of prev. issue.

Looking forward to performance improvements. ^^

**Comment by wainott** [comment]
Found out the /p (preview) option eliminates the performance problem by skipping the exclusions derivation stage in ExclusionDeriver::DeriveExclusions().
The /p option is supposed to generate only a few test cases, but I didn't find any part of the code limiting the number of generated test cases if this option is enabled.
Can anyone chime in to let us know what'd be the implications of using /p option to override the bad performance with many constraints?
