### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/pict#3]
I would like to point out that an identifier like "[`_PICT_H_`](https://github.com/Microsoft/pict/blob/2ff38f4741a3924a96879358f746529d69d5d31e/api/pictapi.h#L1)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jacekczerwonka** [comment]
Fixed.

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/Microsoft/pict/commit/f58851ebd98479e504ff98d59ecc86015a79a9c8 "Deletion of a few underscores").
