### ISSUE TITLE
could you tag a version?

### ISSUE THREAD

**Issue by glsorre** [Microsoft/pict#30]
I am trying to add a formula for pict to homebrew-core and it is required. Thank you in advance.
Reference: https://github.com/Homebrew/homebrew-core/pull/34402

**Comment by jacekczerwonka** [comment]
I've tagged a recent commit. Can you check if it works for you.

**Comment by glsorre** [comment]
I cannot see any tag in the project :( 
<img width="499" alt="screen shot 2018-11-23 at 19 49 07" src="https://user-images.githubusercontent.com/4059141/48957447-e997cb80-ef58-11e8-807c-3ce277306d08.png">

**Comment by jacekczerwonka** [comment]
Give it another go.
