### ISSUE TITLE
Constraints Warning: All or no values satisfy relation

### ISSUE THREAD

**Issue by jy95** [Microsoft/pict#32]
Hello,

I wonder how to deal with this warning when I got this warning. For example :
```
someString: null, "", "$", "\$", "foo"
```

I would like to do something like that : 
```
IF NOT ( [someString] in {foo} ) THEN ....
```

Thanks for your help

**Comment by jacekczerwonka** [comment]
You either have to do:

someString: "", "$", "\$", "foo"
IF NOT ( [someString] in {"\"foo\""} ) THEN [a]=1;

Or

someString: , $, \$, foo
IF NOT ( [someString] in {"foo"} ) THEN [a]=1;

--Jacek

**Comment by jy95** [comment]
Thanks for the answer : the documentation doesn't say anything about your first solution
