### ISSUE TITLE
`make test` failing in Ubuntu 18.04

### ISSUE THREAD

**Issue by stdedos** [microsoft/pict#34]
I have tried to build the project in `Ubuntu 18.04`

After `sudo apt-get install build-essential clang`, `make all test` returns some testing errors (compilation is clean).

I would appreciate if someone could take a look at the failures. I find it hard to read the failing results, and `C++` is not my strongest suit. It could be that one of the failing test cases had UTF-8 test (the input data looked weird when opening the file with `nano`)

Kindly inform me what should I upload.

```
───────┬─────────────────────────────────────────────
       │ File: test/rel.log.failures
───────┼─────────────────────────────────────────────
   1   │ EXP: 4 ACT: 134    /                    /v
   2   │ EXP: 4 ACT: 134    //                   /v
   3   │ EXP: 0 ACT: 2    bug020.txt /d:`      /v
   4   │ EXP: 0 ACT: 134    enc003.txt    /v
   5   │ EXP: 4 ACT: 134    enc001.txt    /v
   6   │ EXP: 4 ACT: 134    enc002.txt    /v
   7   │ EXP: 0 ACT: 134    real037.txt    /v
───────┴─────────────────────────────────────────────
```

**Comment by jacekczerwonka** [comment]
Indeed, these tests run with models encoded as UTF-8. They need cleanup. It all works on Windows en-US but I wouldn't be surprised if they fail on other platforms or Windows versions that use non-Latin script as default. PICT.EXE need to change how it handles input text, especially double-byte character sets but it is a fix I'm not able to spend time on. For now, ignore these test failures.

**Comment by stdedos** [comment]
Thank you 😃
