### ISSUE TITLE
How to debug the code in visual studio 2017 ,can you please explain code flow?

### ISSUE THREAD

**Issue by rajeshangowda** [microsoft/pict#35]

**Comment by jacekczerwonka** [comment]
Assuming you have VS 2017 with VC++ components installed:

Open **pict.sln**.
Right-click on **pictcli** project and set it as Startup Project.
Set a breakpoint in the **execute** function in **pict.cpp**.
Execute **Start Debugging**.

**Comment by rajeshangowda** [comment]
Thank you for your output.
