### ISSUE TITLE
Simple web service to try pict online

### ISSUE THREAD

**Issue by junkboy0315** [microsoft/pict#38]
Hi!

I created a very simple web service to try pict online.

https://pairwise.yuuniworks.com/

This issue is just to say thank you @jacekczerwonka  for inventing such a great tool!

**Comment by jacekczerwonka** [comment]
I'm glad you found a use for it. I added your website to http://pairwise.org/tools. I hope you get some users.

**Comment by eidermauricio** [comment]
CORS does not allow Access for API consumers, Can you please open your webservice? @tam315
