### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/pict#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [Combination](https://github.com/OpenVSP/OpenVSP/blob/73d3e0f2e4326323036a6c7a3f63300882d99f91/src/geom_api/GuiInterface.cpp#L30 "Destructor for Combination")
* [Task::DeallocWorkbuf](https://github.com/Microsoft/pict/blob/2ff38f4741a3924a96879358f746529d69d5d31e/api/task.cpp#L54 "Task::DeallocWorkbuf function")

**Comment by jacekczerwonka** [comment]
Agreed. No functionality deficiency so will get fixed if I ever edit that file for another reason.
