### ISSUE TITLE
Add pre-existing cases

### ISSUE THREAD

**Issue by arturohernandez10** [microsoft/pict#45]
In our case some test configurations may be costly to setup. And we would prefer, to feed available configurations to PICT.  And then have PICT determine what are the missing configurations if any. I know this is a complex request. but it would be very useful. Perhaps any recommendations?

**Comment by jaccz** [comment]
Did you try https://github.com/Microsoft/pict/blob/master/doc/pict.md#seeding? See if this gets you what you want.
