### ISSUE TITLE
Silently crush with massive combination model

### ISSUE THREAD

**Issue by kz-takeuchi** [microsoft/pict#46]
env : Windows 10 Pro with 16GB RAM

input.txt
```
param1: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
param2: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
param3: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
param4: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
param5: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
param6: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
param7: 0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 98, 99
```
- case1
`pict.exe input.txt /o:4`
So in this situation, memory usage increases only for a moment and exit silently.

- case2
`pict_debug.exe input.txt /o:4`
When use self compiled exe with debug mode, the following was displayed.
    ```
    MicroSoft Visual C++ Runtime Library
    
    Debug Error!
    Program:.../pict_debug.exe
    
    abort() has been called
    ```

Is there any solution?

**Comment by jaccz** [comment]
I suspect you're running out of memory and some mem allocation fails. The issue is that you're trying to crunch through a very large combinatorial space. With the above model @ /o:4 you are trying to find a solution packing over 3 billion combinations. This doesn't look like a realistic model, more like a scalability test. :)

**Comment by kz-takeuchi** [comment]
@jaccz 
Thank you for quick response.
Hmm ... , 

Currently PICT.exe runs at "32bit mode" which is limited memory usage up to 2GB.
Do you think following modification options are feasible?
Or, have you already tried and quit for some reason?

- option 1
Use LARGEADDRESSAWARE compile option which extend memory usage from 2GB to 4GB.

- option 2
Modify and compile to 64bit application.

Best Regards,

**Comment by jaccz** [comment]
Yeah, definitely. Try compiling for 64 bit if you haven't yet. On Windows, which my primary environment, compiling as 64-bit always worked well.

**Comment by kz-takeuchi** [comment]
Thank you for your advice.
I'll try to compile 64-bit exe, and report whether the malloc failure occur or not.

**Comment by kz-takeuchi** [comment]
Sorry for the late reply.
I compiled 64-bit exe, and confirmed that it works with 3GB or more of memory.
Sometimes, faced with littler matters, but could be avoided by changing the random seed.
- (Maybe the lack of memory?) 64-bit exe exited 0 and returned null solution however enum GenerationMode was set as Regular.
- 64-bit exe could not complete calculation with much time, however 32-bit exe(download at pairwise.org) complete calculation quickly at same the problem setting.
