### ISSUE TITLE
Can we exclude redundant parameters for some scenarios

### ISSUE THREAD

**Issue by pokrakam** [microsoft/pict#48]
Is there a way to exclude value-dependent parameters for some test cases?
For example if P1 below is negative then P2 and P3 are irrelevant. 
```
P1: -1, 0, 1
P2: A, B, C
P3: X, Y, Z
```
Here PICT will generate 4 scenarios involving P2 and P3 where P1 is -1. However the use case is that -1 makes P2 and P3 irrelevant, thus I only need one test.

Now I can specify a constraint to associate -1 with A&X, but as I understand it this will 'use up' a P2/P3 combination that I want to test in other constellations.

For the simple case where only one additional parameter is redundant, I've worked out a hack to achieve the right effect by adding a blank dummy value and making the two mutually constrained, but it won't work for two or more redundant parameters. 

Example: 
```
P1: -1, 0, 1
P2: A, B, C
```
will generate 
```
~-1     A
~-1     B
~-1     C
```

But if I add a comma at the end of P2 and do this: 
```
P1: -1, 0, 1
P2: A, B, C,

IF [P1] = -1 THEN [P2] = "";
IF [P2] = "" THEN [P1] = -1;
```
I get all the other 0/1 + A/B/C combinations as before and a single -1 test, which is perfect. 
But I can't achieve this with two redundant parameters as per my first example. I've played with groups, but couldn't get the desired result. 
Is this possible with PICT? 
By the way huge thanks for an excellent tool!

**Comment by jaccz** [comment]
The dummy values idea is often very useful. How about this?

```
P1: -1, 0, 1
P2: A, B, C, NA
P3: X, Y, Z, NA

IF [P1] = -1  THEN [P2] =  "NA" AND [P3] =  "NA";
IF [P1] <> -1 THEN [P2] <> "NA" AND [P3] <> "NA";
```

Output:

```
P1      P2      P3
0       C       Z
1       B       Z
1       C       Y
0       A       X
1       C       X
0       B       X
0       A       Y
-1      NA      NA
0       B       Y
1       A       Z
```

These constraints will become long and somewhat tedious to write if you have a lot of parameters and lots of cases where some values make them not matter but for smaller problems, would something like this work?

**Comment by pokrakam** [comment]
Thanks, handy workaround. My use case was a little more complicated with two stages of failures. I've nevertheless managed to make it work. 
The documentation doesn't include any ELSE examples so I overlooked this possibility. I've created PR #49 to add your example above and my extended use case.

**Comment by jaccz** [comment]
Very cool. Appreciated!
