### ISSUE TITLE
Revisit list of available tools

### ISSUE THREAD

**Issue by igabaydulin** [microsoft/pict#50]
Hi! Looks like some of the links to pairwise testing tools are not relevant anymore (http://pairwise.org/tools.asp):
3. [AETG](http://aetgweb.argreenhouse.com/)
4. [IPO (PairTest)](http://www-cse.uta.edu/~ylei/paper/hase.pdf)
5. [TConfig](http://www.site.uottawa.ca/~awilliam/)
6. [TCG (Test Case Generator)](http://csmiss.jpl.nasa.gov/new/set/2000-prop1.doc)
7. [AllPairs](http://www.satisfice.com/testmethod.shtml)
9. [CTS (Combinatorial Test Services)](http://www.alphaworks.ibm.com/tech/cts)
11. [ReduceArray2](http://www.sstc-online.org/proceedings/2004/PDFFiles/GTD683.pdf)
13. [DDA](http://www.public.asu.edu/~rturban/dda.pdf)
15. [OA1](http://www.software-metrics.org/tools_testing.asp)
17. [AllPairs](http://www.mcdowella.demon.co.uk/allPairs.html)
18. [Intelligent Test Case Handler (replaces CTS)](http://alphaworks.ibm.com/tech/whitch)
19. [CaseMaker](http://www.casemakerinternational.com/)
21. [rdExpert](http://www.phadkeassociates.com/index_files/producthome.htm)
23. [SmartTest](http://www.smartwaretechnologies.com/smarttestprod.htm)
24. [EXACT](http://doi.ieeecomputersociety.org/10.1109/COMPSAC.2006.33)
25. [AllPairs](http://engineering.meta-comm.com/allpairs.aspx)
26. [ATD](http://www.atyoursideconsulting.com/products/atd/atd_description.html)
29. [Pairwise Test Case Generator](http://www.testersdesk.com/pairwse_testersdesk.html)
30. [Combo-Test](http://aehrc.com/research/health-data-management-and-semantics/combo-test)
31. [IPO-s](http://www2.computer.org/portal/web/csdl/doi/10.1109/ICSTW.2009.7)
35. [CombTestWeb](http://alarcosj.esi.uclm.es/CombTestWeb/)
39. [tcases](https://code.google.com/p/tcases/)
43. [TechQA](http://pairwise.techqa.org:8080/)

**Comment by igabaydulin** [comment]
7. [This one](https://www.satisfice.com/download/allpairs) can be used I think

**Comment by jaccz** [comment]
Thanks for the headsup. Closing the issue as it isn't really about this project.
