### ISSUE TITLE
A Question regarding capability of the tool

### ISSUE THREAD

**Issue by nnutman** [microsoft/pict#53]
Hi, I'm trying to understand if the tool support this limitation:

item a : 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
item b: 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
item c: 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
more...

Can I create a rule that item a + item b + item c must always be 100, calculate the numbers of each item for example my results should be:
item a = 10
item b =  40
item c = 50 

in any given option the total should be 100 

Nati

**Comment by jaccz** [comment]
Unfortunately, PICT does not support arithmetic expressions of this type. The only option I can think of would be for you to create an expression that essentially enumerates all possible value combinations adding up to 100:

```
[a] = 10 AND [b] = 10 AND [c] = 80 
OR
[a] = 10 AND [b] = 20 AND [c] = 70 
OR
[a] = 10 AND [b] = 30 AND [c] = 60
OR
... 
```

This is obviously very tedious but I'm not sure I see another way out.

**Comment by nnutman** [comment]
Thanks, I'm doing that but I have cases where the options are just too much.

**Comment by nnutman** [comment]
Hi, I have another question, lets say I have these parameters
ItemA: 1,16,64
ItemB: 1,16,64

Can I have a rule that ItemA<=ItemB, without the need to have a line for each item to show item B can need to be equal or greater

**Comment by jaccz** [comment]
This should work:

`[ItemA] <= [ItemB];`
