### ISSUE TITLE
Output as JSON

### ISSUE THREAD

**Issue by redatlantic** [microsoft/pict#55]
Hi, I'd like to humbly request a switch to toggle json output format instead of table-based. 

e.g. 
```
[/] $ pict model /json
[
  {
    "OS": "Win7",
    "Model": "Home"
  },
  {
    "OS": "Win10",
    "Model": "Pro"
  }
]
```

**Comment by jaccz** [comment]
My suggestion here is to create a small tool / script that will take the current output and convert it into whatever you want and pipe one into another. This way we don't have to worry what format of the day is most prevalent and keep adding code to PICT. Works?
