### ISSUE TITLE
pict 中文testcase.txt error

### ISSUE THREAD

**Issue by omaidb** [microsoft/pict#56]
您好,使用pict生成测试用例时,文件名是中文的,会提示错误:Input Error: Couldn't open file

Hello, when using pict to generate test cases, the file name is in Chinese and an error will be prompted: Input Error: Couldn't open file

OS Version: Windows10 x64
pict Version: 3.7.2

示例文件: 在附件中
Sample file: in attachment
[test批量打印快递单.txt](https://github.com/microsoft/pict/files/6384320/test.txt)

**Comment by jaccz** [comment]
See [this issue](https://github.com/microsoft/pict/issues/31).
