### ISSUE TITLE
Edge blocks download[it could damage my pc msg]

### ISSUE THREAD

**Issue by elkevdlt** [microsoft/pict#57]
**Why Edge blocks PICT when i try to download it?...**  Its safe?

![Captura de pantalla](https://user-images.githubusercontent.com/67130091/118384211-b0e18600-b5da-11eb-8cc9-6d110fe80706.png)

**Comment by lvanvugt** [comment]
Same issue here. Could you please provide a zipped pict.exe.

**Comment by jaccz** [comment]
You can override the block. I like the simple .exe instead of a .zip. Just save and go.
