### ISSUE TITLE
Failed to fetch when multiple constraints on one parameter

### ISSUE THREAD

**Issue by hhcc1223** [microsoft/pict#59]
I found that when a variable has multiple constraints, the processing time goes crazy even add one more value to related parameters. Here is an example:
Let variable [A] can be either 0 or 1, and variables [B] - [I] are dependent parameters. If [A] = 0, then [E] - [H] are not valid so that we set them to "N/A". If [A] = 1, then [I] is not valid. So I write this into the txt for testing:

#define parameters
A: 0,1
B: 0,1,3,6,N/A
C: 128,384,N/A
D: 128,256,**384**,N/A
E: 128,256,N/A
F: 7,9,N/A
G: 7,11,N/A
H: 0,1,8,N/A
I: 4,8,N/A

#constraints
if [A] = 0 then [B] = "N/A" else [B] <> "N/A";
if [A] = 0 then [C] = "N/A" else [C] <> "N/A";
if [A] = 0 then [D] = "N/A" else [D] <> "N/A";
if [A] = 0 then [E] = "N/A" else [E] <> "N/A";
if [A] = 0 then [F] = "N/A" else [F] <> "N/A";
if [A] = 0 then [G] = "N/A" else [G] <> "N/A";
if [A] = 0 then [H] = "N/A" else [H] <> "N/A";

if [A] = 1 then [I] = "N/A" else [I] <> "N/A";

If we test above text, it will show failed to fetch on web or simply stuck in Terminal. However, if we decrease the number of values of all parameters to 2 or 3, then it worked[Say I will delete 384 for parameter D]. It seems that constraints can cause exponential increasing processing time.

**Comment by jaccz** [comment]
> It seems that constraints can cause exponential increasing processing time.

This is correct. There's a part of the overall algorithm that behaves that way. Haven't found a better one yet, unfortunately.

**Comment by hhcc1223** [comment]
> > It seems that constraints can cause exponential increasing processing time.
> 
> This is correct. There's a part of the overall algorithm that behaves that way. Haven't found a better one yet, unfortunately.

That's right, currently PICT works best and I'll try to figure out a way to avoid this situation. Thanks for the reply.
