### ISSUE TITLE
Pict failing with collate_byname<char>::collate_byname failed to construct for C.UTF-8

### ISSUE THREAD

**Issue by peternhale** [microsoft/pict#62]
On HEAD of main I am seeing the error `libc++abi: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for C.UTF-8` when running pict.

maxOS Big Sur 11.5.1 (20G80).

The error does not occur when checkout at b10237099713ef0e45f222042cef01dc3507a611

**Comment by jaccz** [comment]
@qykth-git, does seems related to your recent changes?

**Comment by qykth-git** [comment]
It means Mac OS dose not supports `C.UTF-8` locale.
I will check this error.

**Comment by qykth-git** [comment]
Fix was pushed.
I think it might be works on Mac OS.
