### ISSUE TITLE
[feature request] convenient option to output all combinations

### ISSUE THREAD

**Issue by Apteryks** [microsoft/pict#76]
Hi!

While I understand that the merit of this tool is to enable greatly reducing the amount of combinations to test while maintaining a good coverage, I think it'd be nice to have a robust way to invoke the tool to generate all combinations without having to rely on crude hacks such as `pict models.pict /o:$(wc -l models.pict | cut -f1 -d' ')` :-).

One idea would be to support '/o:max'  as a shortcut to test the greatest order possible.

Thank you!

**Comment by jaccz** [comment]
It does not come up very often as a scenario. As you said, it is way more common to want /o:2 than anything else especially the full product but no disagreement on the possible improvement along the lines you specified. Would you like to make a change and send a PR?

**Comment by Apteryks** [comment]
Hi @jaccz!  I've given this a spin; see: https://github.com/microsoft/pict/pull/77.

**Comment by jaccz** [comment]
Thanks!

**Comment by Apteryks** [comment]
Hi @jaccz; would you mind issuing a new release tag which includes this change?  I'd like to be able to refer to a release rather than a commit/main branch, if that's not too much to ask :-).

**Comment by jaccz** [comment]
https://github.com/microsoft/pict/releases/tag/v3.7.3
