### ISSUE TITLE
Release 3.7.4 to publish vcpkg port

### ISSUE THREAD

**Issue by bhardwajs** [microsoft/pict#86]
Following up on #79, to publish a vcpkg port, we need a version number (https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md). Would it be possible to cut a new release (3.7.4) so that a vcpkg port can be published?

I can send a PR to update the version string in `CMakeLists.txt`.

**Comment by jaccz** [comment]
I can publish a new ver. Would you make the changes?
In addition to cmakelists.txt, we'll need to make a change in **/cli/ver.h**.
Or maybe there's a way for cmakelists to key off of that file (I doubt it but maybe?)

--Jacek

**Comment by jaccz** [comment]
Good to go?
https://github.com/microsoft/pict/releases/tag/v3.7.4
