### ISSUE TITLE
Negative value dont work when constraint order 1?

### ISSUE THREAD

**Issue by GuillaumeSoldat** [Microsoft/pict#9]
Hi,

First of all, thank you for this nice tool!

I'm using PICt for few days and I try toi use negative value (use a "~")
I'm not a developer so I just status on an output I obtained and which seems strange.

Considering in a file.txt the following parameters:

Param: param1, ~param2
Value: value1, value2, value3, value4

I tryed to generate output from order 1 and order 2:

![image](https://cloud.githubusercontent.com/assets/16153393/11592155/1cf13a5c-9a9d-11e5-8d73-b2762947ce5e.png)

I understand the output using order 2
=> I force the exhaustif combinatory among all parameters

I DON'T understand the output using order 1
=> I expected only one  value associated to "~param2" because it is combined to one "positive value". This is not relevant to test the "~param2" with other "positive" value in case of order 1.

Thank you in advance for your answer / correction, it would help a lot.

Regards

**Comment by jacekczerwonka** [comment]
This is expected. The order of 1 means "use each value at least once". "Negative testing" only means that there will only be one negative value per test case. Put those two together and the output meets the criteria. PICT does a bit more than necessary and uses "param2" twice; that's a side-effect of how negative testing mode is implemented but the guarantee of "at least once" and "no two negative values in one test" still holds.

To see it better, try a more complex example like this:

Param: param1, ~param2, param3, ~param4
Value: value1, value2, value3, value4, ~value5
Extra: valueA, valueB, ~valueC

So the short answer is: expected. It can be further optimized but in more practical cases, this is not an issue. Hope this helps.
